version: "3"

services:
  app:
    build: .
    depends_on:
      - postgres    
    image: acgomes68/alpine-node:latest
    container_name: node-${APP_NAME}
    command: npm start
    ports:
    - ${APP_PORT}:3000
    volumes:
    - .:/usr/app

  postgres:
    image: postgres:11-alpine
    container_name: postgres-${POSTGRES_DATABASE}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
    ports:
    - ${POSTGRES_PORT}:5432
    volumes:
    - ./data/postgres:/var/lib/postgresql/data

  mongo:
    depends_on:
      - postgres
    image: mvertes/alpine-mongo:latest
    container_name: mongo-${MONGO_DATABASE}
    ports:
    - ${MONGO_PORT}:27017
    volumes:
    - ./data/mongo:/data/db

  redis:
    image: redis:alpine
    container_name: redis-${REDIS_DATABASE}
    ports:
    - ${REDIS_PORT}:6379
    volumes:
    - ./data/redis:/data